## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則話來觀察訓練情形。

-----
使用Lasso去fit wine data 的回歸模型，在alpha 為0.8下 MSE最大，而在Logistic Regression下的模型，MSE最小。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [10]:
# 匯入樣本檔案
wine = datasets.load_wine()

In [18]:
# 切割資料集
x_train, x_test, y_train, y_test = train_test_split(wine.data,wine.target, test_size=0.2, random_state=4)

In [30]:
# 訓練模型 Lasso 01
model = linear_model.Lasso(0.2)
model = model.fit(x_train, y_train)
y_prdic = model.predict(x_test)

In [29]:
# 有些係數變為0
model.coef_

array([-0.        ,  0.        , -0.        ,  0.02547336,  0.        ,
       -0.        , -0.15617061,  0.        , -0.        ,  0.09481945,
       -0.        , -0.        , -0.00145954])

In [31]:
mean_squared_error(y_prdic, y_test)

0.1586255520439096

In [32]:
# 訓練模型 Lasso 02
model = linear_model.Lasso(0.8)
model = model.fit(x_train, y_train)
y_prdic = model.predict(x_test)

In [33]:
# 有些係數變為0
model.coef_

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
       -0.        , -0.        ,  0.        , -0.        ,  0.00040687,
       -0.        , -0.        , -0.0016002 ])

In [34]:
mean_squared_error(y_prdic, y_test)

0.42340291575000066

In [40]:
# 訓練模型 Logistic Regression 03
model = linear_model.LogisticRegression()
model = model.fit(x_train, y_train)
y_prdic = model.predict(x_test)

In [37]:
# 係數
model.coef_

array([[-6.82859668e-01,  7.19707960e-01,  9.78123381e-01,
        -5.71328117e-01, -3.15688724e-02,  3.00522569e-01,
         1.11716205e+00, -3.43541787e-02, -4.90152098e-01,
        -1.05390348e-02, -1.54184470e-01,  9.61330351e-01,
         1.81479193e-02],
       [ 9.27922692e-01, -1.04718094e+00, -6.96493690e-01,
         2.37579965e-01,  8.45544696e-03,  8.54092990e-02,
         4.69506561e-01,  5.63010510e-01,  5.93849824e-01,
        -1.81380329e+00,  9.34720557e-01,  8.37098156e-02,
        -1.40254226e-02],
       [-4.72180741e-01,  6.31034394e-01, -6.36847580e-02,
         1.56380289e-01,  3.13408129e-02, -7.52374558e-01,
        -1.62587954e+00, -1.31786835e-01, -7.01391159e-01,
         1.03384290e+00, -4.87953686e-01, -1.15357424e+00,
         1.40302536e-04]])

In [38]:
mean_squared_error(y_prdic, y_test)

0.027777777777777776

In [44]:
# 訓練模型 Ridge Regression04
model = linear_model.Ridge(0.2)
model = model.fit(x_train, y_train)
y_prdic = model.predict(x_test)

In [45]:
# 係數有很小很小但不為0的係數
model.coef_

array([-0.10830293,  0.016849  , -0.21618698,  0.04636497,  0.00035849,
        0.11858429, -0.32263589, -0.16387406,  0.03660804,  0.07613104,
       -0.15191262, -0.28316191, -0.00075551])

In [46]:
mean_squared_error(y_prdic, y_test)

0.06720946189122684

In [47]:
# 訓練模型 Ridge Regression04
model = linear_model.Ridge(0.8)
model = model.fit(x_train, y_train)
y_prdic = model.predict(x_test)

In [48]:
# 係數有很小很小但不為0的係數
model.coef_

array([-0.10651972,  0.01744693, -0.20563903,  0.04546906,  0.00040835,
        0.10345894, -0.314578  , -0.11444492,  0.03528817,  0.07732728,
       -0.13867993, -0.27637491, -0.0007665 ])

In [49]:
mean_squared_error(y_prdic, y_test)

0.06771633806407489